# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f76b32fed74b9e98c695635b8e96c0aff1dc8a40b9189fcd31ba81222bd4127a11f9027eef67497e731e43918d9028eecc37c14fef65aab32cafd1ddaa91621

test:
  secret_key_base: d7c6a42d15fd1365543cf8bfdc0c661cc72f99958948f66e35d28b336071cad06b280fed57ec312f201fe43b176faffcbdb3684ab73536c665b2e2defdcc463e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
